In [1]:
from numpy import asarray
from sklearn.preprocessing import PolynomialFeatures

data=asarray([[2, 3], [2, 3], [2, 3]])
print("Original data:")
print(data)

trans=PolynomialFeatures(degree=2)
data =trans.fit_transform(data)
print("\nTransformed data:")
print(data)


Original data:
[[2 3]
 [2 3]
 [2 3]]

Transformed data:
[[1. 2. 3. 4. 6. 9.]
 [1. 2. 3. 4. 6. 9.]
 [1. 2. 3. 4. 6. 9.]]


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("../data/profit.csv")
df

gold  estate    cryto  stock  profit
0     14.96   41.76  1024.07  73.17  463.26
1     25.18   62.96  1020.04  59.08  444.37
2      5.11   39.40  1012.16  92.14  488.56
3     20.86   57.32  1010.24  76.64  446.48
4     10.82   37.50  1009.23  96.62  473.90
...     ...     ...      ...    ...     ...
9563  16.65   49.69  1014.01  91.00  460.03
9564  13.19   39.18  1023.67  66.78  469.62
9565  31.32   74.33  1012.92  36.48  429.57
9566  24.48   69.45  1013.86  62.39  435.74
9567  21.60   62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9568 entries, 0 to 9567
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   gold    9568 non-null   float64
 1   estate  9568 non-null   float64
 2   cryto   9568 non-null   float64
 3   stock   9568 non-null   float64
 4   profit  9568 non-null   float64
dtypes: float64(5)
memory usage: 373.9 KB


In [4]:
df.shape

(9568, 5)

In [5]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]
from sklearn.preprocessing import PolynomialFeatures
poly_fe=PolynomialFeatures(degree=2)
poly_data=poly_fe.fit_transform(X)
X_poly=pd.DataFrame(data=poly_data)
print(X_poly)


       0      1      2        3      4         5          6           7   \
0     1.0  14.96  41.76  1024.07  73.17  223.8016   624.7296  15320.0872   
1     1.0  25.18  62.96  1020.04  59.08  634.0324  1585.3328  25684.6072   
2     1.0   5.11  39.40  1012.16  92.14   26.1121   201.3340   5172.1376   
3     1.0  20.86  57.32  1010.24  76.64  435.1396  1195.6952  21073.6064   
4     1.0  10.82  37.50  1009.23  96.62  117.0724   405.7500  10919.8686   
...   ...    ...    ...      ...    ...       ...        ...         ...   
9563  1.0  16.65  49.69  1014.01  91.00  277.2225   827.3385  16883.2665   
9564  1.0  13.19  39.18  1023.67  66.78  173.9761   516.7842  13502.2073   
9565  1.0  31.32  74.33  1012.92  36.48  980.9424  2328.0156  31724.6544   
9566  1.0  24.48  69.45  1013.86  62.39  599.2704  1700.1360  24819.2928   
9567  1.0  21.60  62.52  1017.23  67.87  466.5600  1350.4320  21972.1680   

             8          9           10         11            12          13  \
0     10

In [10]:
from sklearn.preprocessing import MinMaxScaler
mm_scaler=MinMaxScaler()
scaled_data=mm_scaler.fit_transform(X_poly)
X_scaled=pd.DataFrame(data=scaled_data,columns=X_poly.columns)
print(X_scaled)

       0         1         2         3         4         5         6   \
0     0.0  0.372521  0.291815  0.771591  0.638204  0.160513  0.208762   
1     0.0  0.662040  0.669039  0.671863  0.449330  0.459107  0.571150   
2     0.0  0.093484  0.249822  0.476862  0.892493  0.016622  0.049036   
3     0.0  0.539660  0.568683  0.429349  0.684718  0.314340  0.424159   
4     0.0  0.255241  0.216014  0.404355  0.952547  0.082829  0.126152   
...   ...       ...       ...       ...       ...       ...       ...   
9563  0.0  0.420397  0.432918  0.522643  0.877212  0.199397  0.285197   
9564  0.0  0.322380  0.245907  0.761693  0.552547  0.124247  0.168040   
9565  0.0  0.835977  0.871352  0.495669  0.146381  0.711612  0.851327   
9566  0.0  0.642210  0.784520  0.518931  0.493700  0.433805  0.614460   
9567  0.0  0.560623  0.661210  0.602326  0.567158  0.337209  0.482534   

            7         8         9         10        11        12        13  \
0     0.379381  0.380802  0.183189  0.304203 

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [12]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [13]:
print(regressor.intercept_)
print(regressor.coef_)

493.3261587954307
[ 0.00000000e+00 -2.06635583e+02 -1.54533859e+02  6.22766205e+02
  2.94863029e+02  2.47606060e+01  2.74469340e+01  1.11600459e+02
 -1.38675471e+01 -3.66422809e+00  1.28750918e+02  4.24375844e-01
 -6.14202828e+02 -2.77789591e+02 -1.80343115e+01]


In [14]:
print('Score or R-Squared:', regressor.score(X_train, y_train))


Score or R-Squared: 0.9377092268931406


In [15]:
y_pred=regressor.predict(X_test)
np.set_printoptions(precision=2)
print("Predicted values:")
print(y_pred)

Predicted values:
[454.99 439.05 434.93 ... 483.29 435.56 455.44]


In [16]:
import numpy as np
from sklearn import metrics
y_test_pred=regressor.predict(X_test)
print("Score or R-Squared:", metrics.r2_score(y_test, y_test_pred))
print("Mean Absolute Error:", metrics.mean_absolute_error(y_test, y_test_pred))

print("Root Mean Squared Error:", np.sqrt(metrics.mean_squared_error(y_test, y_test_pred)))

Score or R-Squared: 0.9382776706597605
Mean Absolute Error: 3.3513498086710864
Root Mean Squared Error: 4.231200085537503


In [17]:
from sklearn.model_selection import GridSearchCV
model = LinearRegression()
param_space = {'copy_X': [True, False],
               'fit_intercept': [True, False],
               'n_jobs': [1,5,10,15,None],'positive':[True,False]}
grid_search = GridSearchCV(model, param_space, cv=5)
grid_search.fit(X_train, y_train)
print("Best parameters found: ", grid_search.best_params_)
print("Best score found: ", grid_search.best_score_)


Best parameters found:  {'copy_X': True, 'fit_intercept': True, 'n_jobs': 1, 'positive': False}
Best score found:  0.9374725137418858


In [18]:
bestModel=LinearRegression()
bestModel.set_params(copy_X=True,fit_intercept=True,n_jobs=1,positive=False)
bestModel.fit(X_train, y_train)
print("Score or R-Squared:", bestModel.score(X_train, y_train))
y_pred=bestModel.predict(X_test)
print("Score or R-Squared:", metrics.r2_score(y_test, y_pred))
print("Mean Absolute Error:", metrics.mean_absolute_error(y_test, y_pred))
print("Root Mean Squared Error:", np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print("Mean Absolute Percentage Error:", np.mean(np.abs((y_test - y_pred) / y_test)) * 100)

Score or R-Squared: 0.9377092268931406
Score or R-Squared: 0.9382776706597605
Mean Absolute Error: 3.3513498086710864
Root Mean Squared Error: 4.231200085537503
Mean Absolute Percentage Error: 0.7383717990753909


In [ ]:
#Xây dựng ứng dụng dự báo   profit
# xgold =15.82
# xestate = 47.50
# xcrypto = 1007
# xstock = 100.62

xgold = float(input("Enter Gold price: "))
xestate = float(input("Enter Estate price: "))
xcrypto = float(input("Enter Crypto price: "))
xstock = float(input("Enter Stock price: "))
scaled_value=poly_fe.transform([[xgold, xestate, xcrypto, xstock]])
scaled_value = mm_scaler.transform(scaled_value)
predicted_profit = bestModel.predict(scaled_value)
print(f"Predicted profit for Gold: {xgold}, Estate: {xestate}, Crypto: {xcrypto}, Stock: {xstock} is: {predicted_profit[0]:.2f}")
